version: '3.8'

services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "8000:5000"
    volumes:
      - .:/app

  db:
      image: mongo:latest
      hostname: test_mongodb
      environment:
        - MONGO_INITDB_DATABASE=users
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass